name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  codeowners-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2

      - name: GitHub CODEOWNERS Validator
        uses: mszostok/codeowners-validator@v0.6.0
        with:
          checks: "files,duppatterns,syntax"
          repository_path: "."
